<?php

/**
 * @file DocumentPreviewService.php
 * @brief Safe inline-preview classification and bounded text-file preparation.
 * @author Frank Willeke
 */

declare(strict_types=1);

namespace Pulse\Services;

/**
 * @brief Describes browser-native previews and prepares passive framed text representations.
 */
final class DocumentPreviewService
{
	public const KIND_DOWNLOAD = 'download';
	public const KIND_MARKDOWN = 'markdown';
	public const KIND_TEXT = 'text';
	public const KIND_CSV = 'csv';
	public const KIND_JSON = 'json';
	public const KIND_PDF = 'pdf';
	public const KIND_IMAGE = 'image';
	public const KIND_AUDIO = 'audio';
	public const KIND_VIDEO = 'video';

	private const MAX_TEXT_PREVIEW_BYTES = 2097152;
	private const MAX_CSV_ROWS = 500;
	private const MAX_CSV_COLUMNS = 50;
	private const MAX_CSV_CELL_BYTES = 32768;

	/** @var array<int, string> */
	private const IMAGE_MIME_TYPES = [
		'image/gif',
		'image/jpeg',
		'image/png',
		'image/webp',
		'image/avif',
	];

	/** @var array<int, string> */
	private const AUDIO_MIME_TYPES = [
		'audio/mpeg',
		'audio/mp4',
		'audio/x-m4a',
		'audio/aac',
		'audio/ogg',
		'audio/webm',
		'audio/wav',
		'audio/x-wav',
		'audio/flac',
		'audio/x-flac',
	];

	/** @var array<int, string> */
	private const VIDEO_MIME_TYPES = [
		'video/mp4',
		'video/webm',
		'video/quicktime',
		'video/ogg',
	];

	/** @brief Returns the safest useful portal presentation for one document. */
	public function Kind(array $document): string
	{
		if ((string)($document['storage_type'] ?? '') === 'text')
		{
			return self::KIND_MARKDOWN;
		}

		$mimeType = $this->MimeType($document);
		$extension = strtolower(pathinfo((string)($document['original_filename'] ?? ''), PATHINFO_EXTENSION));

		if ($mimeType === 'application/pdf')
		{
			return self::KIND_PDF;
		}

		if (in_array($mimeType, self::IMAGE_MIME_TYPES, true))
		{
			return self::KIND_IMAGE;
		}

		if ($mimeType === 'application/ogg')
		{
			return $extension === 'ogv' ? self::KIND_VIDEO : self::KIND_AUDIO;
		}

		if (in_array($mimeType, self::AUDIO_MIME_TYPES, true))
		{
			return self::KIND_AUDIO;
		}

		if (in_array($mimeType, self::VIDEO_MIME_TYPES, true))
		{
			return in_array($extension, ['m4a', 'm4b'], true) ? self::KIND_AUDIO : self::KIND_VIDEO;
		}

		if (in_array($mimeType, ['text/markdown', 'text/x-markdown'], true))
		{
			return self::KIND_MARKDOWN;
		}

		if (in_array($mimeType, ['text/csv', 'application/csv'], true) || in_array($extension, ['csv', 'tsv'], true))
		{
			return self::KIND_CSV;
		}

		if (in_array($mimeType, ['application/json', 'text/json'], true) || $extension === 'json')
		{
			return self::KIND_JSON;
		}

		if ($mimeType === 'text/plain')
		{
			return in_array($extension, ['md', 'markdown'], true) ? self::KIND_MARKDOWN : self::KIND_TEXT;
		}

		return self::KIND_DOWNLOAD;
	}

	/** @brief Returns whether a document has a safe direct portal representation. */
	public function IsViewable(array $document): bool
	{
		return $this->Kind($document) !== self::KIND_DOWNLOAD;
	}

	/** @brief Returns whether the preview is an HTML frame generated by Pulse. */
	public function IsTextFrame(array $document): bool
	{
		return in_array($this->Kind($document), [
			self::KIND_MARKDOWN,
			self::KIND_TEXT,
			self::KIND_CSV,
			self::KIND_JSON,
		], true);
	}

	/** @brief Returns a browser media/content type for raw passive assets. */
	public function RawContentType(array $document): ?string
	{
		$kind = $this->Kind($document);

		if (!in_array($kind, [self::KIND_PDF, self::KIND_IMAGE, self::KIND_AUDIO, self::KIND_VIDEO], true))
		{
			return null;
		}

		$mimeType = $this->MimeType($document);

		if ($mimeType === 'application/ogg')
		{
			return $kind === self::KIND_VIDEO ? 'video/ogg' : 'audio/ogg';
		}

		if ($kind === self::KIND_AUDIO && $mimeType === 'video/mp4')
		{
			return 'audio/mp4';
		}

		return $mimeType !== '' ? $mimeType : null;
	}

	/**
	 * @brief Builds a safe bounded HTML-frame view model for a text-like document.
	 * @param array<string, mixed> $document Document snapshot or current document.
	 * @param string|null $path Verified private path for an uploaded file.
	 * @return array<string, mixed>|null Prepared preview or null when unavailable.
	 */
	public function BuildTextFrame(array $document, ?string $path): ?array
	{
		$kind = $this->Kind($document);

		if (!$this->IsTextFrame($document))
		{
			return null;
		}

		if ((string)($document['storage_type'] ?? '') === 'text')
		{
			return [
				'kind' => self::KIND_MARKDOWN,
				'content' => (string)($document['text_content'] ?? ''),
				'rows' => [],
				'truncated' => false,
			];
		}

		if ($path === null || !is_file($path) || !is_readable($path))
		{
			return null;
		}

		if ($kind === self::KIND_CSV)
		{
			return $this->BuildCsvPreview($path, $document);
		}

		[$content, $truncated] = $this->ReadText($path);

		if ($kind === self::KIND_JSON && !$truncated)
		{
			$decoded = json_decode($content, true, 512, JSON_INVALID_UTF8_SUBSTITUTE);

			if (json_last_error() === JSON_ERROR_NONE)
			{
				$encoded = json_encode($decoded, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

				if (is_string($encoded))
				{
					$truncated = strlen($encoded) > self::MAX_TEXT_PREVIEW_BYTES;
					$content = substr($encoded, 0, self::MAX_TEXT_PREVIEW_BYTES);
				}
			}
		}

		return [
			'kind' => $kind,
			'content' => $content,
			'rows' => [],
			'truncated' => $truncated,
		];
	}

	/** @return array{0: string, 1: bool} @brief Reads a bounded UTF-8-oriented text preview. */
	private function ReadText(string $path): array
	{
		$handle = fopen($path, 'rb');

		if ($handle === false)
		{
			return ['', false];
		}

		try
		{
			$content = fread($handle, self::MAX_TEXT_PREVIEW_BYTES + 1);
		}
		finally
		{
			fclose($handle);
		}

		if (!is_string($content))
		{
			return ['', false];
		}

		$truncated = strlen($content) > self::MAX_TEXT_PREVIEW_BYTES;
		$content = substr($content, 0, self::MAX_TEXT_PREVIEW_BYTES);
		return [$this->NormalizeText($content), $truncated];
	}

	/** @return array<string, mixed> @brief Parses a bounded CSV/TSV preview without loading the entire file. */
	private function BuildCsvPreview(string $path, array $document): array
	{
		$handle = fopen($path, 'rb');

		if ($handle === false)
		{
			return ['kind' => self::KIND_CSV, 'content' => '', 'rows' => [], 'truncated' => false];
		}

		$extension = strtolower(pathinfo((string)($document['original_filename'] ?? ''), PATHINFO_EXTENSION));
		$sample = fread($handle, 16384);
		$delimiter = $extension === 'tsv' ? "\t" : $this->DetectDelimiter(is_string($sample) ? $sample : '');
		rewind($handle);
		$rows = [];
		$truncated = false;

		try
		{
			while (count($rows) < self::MAX_CSV_ROWS)
			{
				$position = ftell($handle);

				if (is_int($position) && $position >= self::MAX_TEXT_PREVIEW_BYTES)
				{
					$truncated = true;
					break;
				}

				$row = fgetcsv($handle, 0, $delimiter, '"', '');

				if ($row === false)
				{
					break;
				}

				if (count($row) > self::MAX_CSV_COLUMNS)
				{
					$row = array_slice($row, 0, self::MAX_CSV_COLUMNS);
					$truncated = true;
				}

				$rows[] = array_map(
					fn (?string $cell): string => $this->NormalizeText(substr((string)$cell, 0, self::MAX_CSV_CELL_BYTES)),
					$row
				);
			}

			if (!feof($handle))
			{
				$truncated = true;
			}
		}
		finally
		{
			fclose($handle);
		}

		return [
			'kind' => self::KIND_CSV,
			'content' => '',
			'rows' => $rows,
			'truncated' => $truncated,
		];
	}

	/** @brief Selects a likely delimiter from the first physical line. */
	private function DetectDelimiter(string $sample): string
	{
		$line = strtok($sample, "\r\n");
		$line = is_string($line) ? $line : '';
		$bestDelimiter = ',';
		$bestColumns = 1;

		foreach ([',', ';', "\t", '|'] as $delimiter)
		{
			$columns = count(str_getcsv($line, $delimiter, '"', ''));

			if ($columns > $bestColumns)
			{
				$bestColumns = $columns;
				$bestDelimiter = $delimiter;
			}
		}

		return $bestDelimiter;
	}

	/** @brief Replaces invalid/binary bytes conservatively before HTML escaping. */
	private function NormalizeText(string $content): string
	{
		$content = str_replace("\0", '', $content);

		if (preg_match('//u', $content) === 1)
		{
			return $content;
		}

		return preg_replace('/[^\x09\x0A\x0D\x20-\x7E]/', "\xEF\xBF\xBD", $content) ?? '';
	}

	/** @brief Returns a normalized stored MIME type. */
	private function MimeType(array $document): string
	{
		return strtolower(trim((string)($document['mime_type'] ?? '')));
	}
}
